#!/usr/bin/env bash
# optimize-node.sh
# 高带宽代理节点一键优化脚本 (Debian/Ubuntu/CentOS/RHEL/Alma/Rocky...)
# 功能：
# - 自动检测包管理器并安装必要工具 (ethtool, iproute2, irqbalance 等)
# - 优化 Sysctl 网络参数 (BBR + fq, TCP buffer 调优)
# - 开启网卡高级功能 (GRO/GSO/TSO) 并尝试开启多队列 (Multiqueue)
# - 安装 irqbalance 自动管理中断，替代不稳定的手动绑核
# - 设置 CPU 性能模式 (Performance Governor)
# - 提高系统文件描述符限制 (ulimit)
# - 创建 Systemd 服务以确保重启后网络优化依然生效（动态检测网卡）
#
# 使用方法 (需 root 权限):
#   sudo bash optimize-node.sh
#

set -euo pipefail

# --- 全局变量 ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
BACKUP_DIR="/root/optimize-node-backups-${TIMESTAMP}"
SYSCTL_CONF="/etc/sysctl.d/99-optimizations.conf"
LIMITS_CONF="/etc/security/limits.conf"
SYSTEMD_LIMITS_CONF="/etc/systemd/system.conf.d/90-optimizations.conf"
NETWORK_APPLY_SCRIPT="/usr/local/sbin/network-optimize-apply.sh"
NETWORK_SERVICE_UNIT="/etc/systemd/system/network-optimize.service"

# --- 辅助函数 ---

log() {
    echo -e "\033[32m[OPTIMIZE]\033[0m $*"
}

warn() {
    echo -e "\033[33m[WARNING]\033[0m $*" >&2
}

error() {
    echo -e "\033[31m[ERROR]\033[0m $*" >&2
}

# 检查是否以 root 运行
check_root() {
    if [ "$(id -u)" -ne 0 ]; then
        error "此脚本必须以 root 权限运行。请使用 sudo。"
        exit 1
    fi
}

# 备份文件
backup_file() {
    local f="$1"
    if [ -e "$f" ]; then
        mkdir -p "${BACKUP_DIR}$(dirname "$f")"
        cp -a "$f" "${BACKUP_DIR}${f}.${TIMESTAMP}.bak"
        log "已备份文件: $f -> ${BACKUP_DIR}${f}.${TIMESTAMP}.bak"
    fi
}

# 检测并安装依赖包
install_packages() {
    local pkg_manager=""
    if command -v apt-get >/dev/null 2>&1; then
        pkg_manager="apt"
    elif command -v dnf >/dev/null 2>&1; then
        pkg_manager="dnf"
    elif command -v yum >/dev/null 2>&1; then
        pkg_manager="yum"
    elif command -v zypper >/dev/null 2>&1; then
        pkg_manager="zypper"
    fi

    log "检测到包管理器: ${pkg_manager:-未知}"

    if [ -z "$pkg_manager" ]; then
        warn "未找到支持的包管理器，跳过依赖安装。"
        return
    fi

    log "正在安装必要工具 (ethtool, iproute2, irqbalance, htop)..."
    case "$pkg_manager" in
        apt)
            apt-get update -y
            DEBIAN_FRONTEND=noninteractive apt-get install -y ethtool iproute2 iftop htop sysstat irqbalance || true
            ;;
        dnf)
            dnf install -y ethtool iproute iftop htop sysstat irqbalance || true
            ;;
        yum)
            yum install -y ethtool iproute iftop htop sysstat irqbalance || true
            ;;
        zypper)
            zypper install -y ethtool iproute2 iftop htop sysstat irqbalance || true
            ;;
    esac
    
    # 确保 irqbalance 已启动
    if command -v systemctl >/dev/null 2>&1; then
        systemctl enable --now irqbalance || warn "无法启动 irqbalance 服务"
    fi
}

# 配置 Sysctl 参数
configure_sysctl() {
    log "配置 Sysctl 网络参数..."
    backup_file "$SYSCTL_CONF"

    cat > "${SYSCTL_CONF}" <<'EOF'
# /etc/sysctl.d/99-optimizations.conf
# Generated by optimize-node.sh

# --- 拥塞控制与队列 ---
# 使用 fq + bbr 组合
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# --- TCP 缓冲区优化 (针对高 BDP 链路) ---
# max buffer size 64MB
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864

# --- 连接处理与并发 ---
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 10
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 250000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_mtu_probing = 1

# --- 其他安全与性能 ---
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_slow_start_after_idle = 0
EOF

    log "应用 Sysctl 参数..."
    sysctl --system >/dev/null 2>&1 || warn "sysctl 应用部分参数失败，可能是容器环境限制。"

    # 检查 BBR 是否生效
    if sysctl net.ipv4.tcp_congestion_control | grep -q bbr; then
        log "BBR 已成功启用。"
    else
        warn "BBR 未启用。尝试加载模块..."
        modprobe tcp_bbr 2>/dev/null || true
        sysctl -w net.ipv4.tcp_congestion_control=bbr 2>/dev/null || true
        if ! sysctl net.ipv4.tcp_congestion_control | grep -q bbr; then
            warn "内核可能不支持 BBR，请检查内核版本或虚拟化架构。"
        fi
    fi
}

# 配置系统文件描述符限制
configure_limits() {
    log "配置系统文件描述符限制 (ulimit)..."
    
    # 1. 修改 /etc/security/limits.conf (幂等性检查)
    backup_file "$LIMITS_CONF"
    if ! grep -q "Added by optimize-node.sh" "$LIMITS_CONF"; then
        cat >> "$LIMITS_CONF" <<'EOF'

# Added by optimize-node.sh - increase file descriptors
*               soft    nofile          1000000
*               hard    nofile          1000000
root            soft    nofile          1000000
root            hard    nofile          1000000
EOF
        log "已更新 $LIMITS_CONF"
    else
        log "$LIMITS_CONF 中已包含优化配置，跳过。"
    fi

    # 2. 修改 Systemd 全局配置
    if command -v systemctl >/dev/null 2>&1; then
        mkdir -p "$(dirname "$SYSTEMD_LIMITS_CONF")"
        backup_file "$SYSTEMD_LIMITS_CONF"
        cat > "$SYSTEMD_LIMITS_CONF" <<'EOF'
[Manager]
DefaultLimitNOFILE=1000000
EOF
        log "已创建 Systemd 全局限制配置: $SYSTEMD_LIMITS_CONF"
        systemctl daemon-reload || true
    fi
}

# 设置 CPU 性能模式
set_cpu_performance() {
    log "尝试设置 CPU 为 performance 模式..."
    if command -v cpufreq-set >/dev/null 2>&1; then
        for cpu in /sys/devices/system/cpu/cpu[0-9]*; do
            cpufreq-set -c "${cpu##*cpu}" -g performance >/dev/null 2>&1 || true
        done
    elif [ -d /sys/devices/system/cpu ]; then
        for g in /sys/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor; do
            if [ -w "$g" ]; then
                echo performance > "$g" || true
            fi
        done
    fi
}

# 创建网络优化脚本 (动态检测)
create_network_script() {
    log "创建网络优化启动脚本..."
    backup_file "$NETWORK_APPLY_SCRIPT"

    # 注意：这里写入的脚本会在每次启动时运行，因此它必须是动态检测环境的
    cat > "$NETWORK_APPLY_SCRIPT" <<'EOF'
#!/usr/bin/env bash
# network-optimize-apply.sh
# 启动时自动应用网卡优化 (Ethtool, TC)
# 此脚本动态检测主网卡，适应虚拟机克隆或配置变更

set -u

# 动态检测主网卡 (访问公共 DNS 的路由接口)
PRIMARY_IFACE="$(ip route get 8.8.8.8 2>/dev/null | awk '/dev/ {for(i=1;i<=NF;i++){if($i=="dev"){print $(i+1); exit}}}')"
if [ -z "$PRIMARY_IFACE" ]; then
    # 回退：第一个非 lo 的接口
    PRIMARY_IFACE="$(ip -o link show | awk -F': ' '{print $2}' | grep -v lo | head -n1)"
fi

if [ -z "$PRIMARY_IFACE" ]; then
    echo "无法检测到主网卡，跳过网络优化。"
    exit 0
fi

echo "正在优化网卡: ${PRIMARY_IFACE}"

# 1. Ethtool 优化 (GRO/GSO/TSO)
if command -v ethtool >/dev/null 2>&1; then
    ethtool -K "${PRIMARY_IFACE}" gro on gso on tso on 2>/dev/null || true
    
    # 尝试开启多队列 (Multiqueue)
    # 设置队列数为 min(CPU核数, 网卡最大支持数)
    CPU_COUNT="$(nproc --all)"
    MAX_COMBINED=$(ethtool -l "${PRIMARY_IFACE}" 2>/dev/null | awk '/Combined:/ {print $2}' | head -n1)
    
    if [ -n "${MAX_COMBINED}" ] && [ "${MAX_COMBINED}" -gt 0 ]; then
        TARGET=$(( CPU_COUNT > MAX_COMBINED ? MAX_COMBINED : CPU_COUNT ))
        echo "设置网卡队列数: ${TARGET} (最大支持: ${MAX_COMBINED})"
        ethtool -L "${PRIMARY_IFACE}" combined "${TARGET}" 2>/dev/null || true
    fi
    
    # 增大 Ring Buffer (可选，视网卡支持情况而定，这里暂不强制设置以免报错)
    # ethtool -G "${PRIMARY_IFACE}" rx 4096 tx 4096 2>/dev/null || true
fi

# 2. TC Qdisc 优化 (fq)
if command -v tc >/dev/null 2>&1; then
    # 仅当当前 qdisc 不是 fq 时才设置，避免不必要的报错
    CURRENT_QDISC=$(tc qdisc show dev "${PRIMARY_IFACE}" | head -n1 | awk '{print $2}')
    if [ "$CURRENT_QDISC" != "fq" ]; then
        tc qdisc replace dev "${PRIMARY_IFACE}" root fq 2>/dev/null || true
    fi
fi

# 3. CPU 性能模式 (再次确保生效)
if [ -d /sys/devices/system/cpu ]; then
    for g in /sys/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor; do
        [ -w "$g" ] && echo performance > "$g" 2>/dev/null || true
    done
fi

exit 0
EOF

    chmod +x "$NETWORK_APPLY_SCRIPT"
    log "网络优化脚本已创建: $NETWORK_APPLY_SCRIPT"
}

# 创建 Systemd 服务
create_systemd_service() {
    log "配置 Systemd 开机自启服务..."
    backup_file "$NETWORK_SERVICE_UNIT"

    cat > "$NETWORK_SERVICE_UNIT" <<EOF
[Unit]
Description=Apply Network Optimizations (Ethtool/TC)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${NETWORK_APPLY_SCRIPT}
RemainAfterExit=yes
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload || true
    systemctl enable --now network-optimize.service || warn "无法启用 network-optimize.service"
    log "Systemd 服务已启用: network-optimize.service"
}

# --- 主流程 ---

main() {
    mkdir -p "${BACKUP_DIR}"
    log "开始优化流程... 备份目录: ${BACKUP_DIR}"

    check_root
    install_packages
    configure_sysctl
    configure_limits
    set_cpu_performance
    create_network_script
    create_systemd_service

    log "===== 优化完成 ====="
    log "1. 请重启服务器以确保所有更改（特别是 ulimit 和内核参数）完全生效。"
    log "2. 验证命令:"
    log "   - 查看 BBR: sysctl net.ipv4.tcp_congestion_control"
    log "   - 查看队列: tc qdisc show"
    log "   - 查看服务: systemctl status network-optimize.service"
    log "   - 查看 ulimit: ulimit -n (需重新登录)"
}

main "$@"
