#!/bin/bash

# 定义颜色
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
SKYBLUE='\033[0;36m'
PLAIN='\033[0m'

# 核心变量默认值
EXTERNAL_NODES_FILE="/root/xui_external_nodes.txt"
UPDATER_SCRIPT="/root/xui_sub_merger.sh"
WEB_ROOT="/var/www/html"

clear
echo -e "${SKYBLUE}#############################################################${PLAIN}"
echo -e "${SKYBLUE}#                                                           #${PLAIN}"
echo -e "${SKYBLUE}#           X-UI 本地订阅 + 外部节点 聚合工具               #${PLAIN}"
echo -e "${SKYBLUE}#                                                           #${PLAIN}"
echo -e "${SKYBLUE}#############################################################${PLAIN}"
echo ""

# 1. 检查环境
if ! command -v curl &> /dev/null; then
    echo -e "${RED}错误: 未检测到 curl，请先安装: apt install curl 或 yum install curl${PLAIN}"
    exit 1
fi

# 2. 获取本机 X-UI 订阅地址
echo -e "${YELLOW}[步骤 1/5] 配置本机 X-UI${PLAIN}"
echo -e "请登录你的 X-UI 面板 -> 面板设置 -> 复制【订阅地址】"
echo -e "提示: 如果本机有公网IP，建议将地址中的 IP 改为 127.0.0.1 以加快速度并保护隐私。"
read -p "请输入 X-UI 订阅链接: " XUI_URL

if [ -z "$XUI_URL" ]; then
    echo -e "${RED}错误: 订阅链接不能为空！${PLAIN}"
    exit 1
fi

# 3. 获取外部节点链接
echo -e "\n${YELLOW}[步骤 2/5] 添加外部 Vless 节点${PLAIN}"
echo -e "请逐条输入其他 VPS 的 vless:// 链接。"
echo -e "输入完毕后，直接按回车键结束。"

# 清空或创建外部节点文件
> "$EXTERNAL_NODES_FILE"

count=1
while true; do
    read -p "请输入第 ${count} 个链接 (回车结束): " link
    if [ -z "$link" ]; then
        break
    fi
    echo "$link" >> "$EXTERNAL_NODES_FILE"
    ((count++))
done
echo -e "${GREEN}已保存 $((count-1)) 个外部节点到 $EXTERNAL_NODES_FILE${PLAIN}"

# 4. 配置 Web 目录和文件名
echo -e "\n${YELLOW}[步骤 3/5] 配置发布路径${PLAIN}"
read -p "请输入 Nginx/Web 根目录 (默认: $WEB_ROOT): " input_web_root
if [ -n "$input_web_root" ]; then
    WEB_ROOT="$input_web_root"
fi

# 确保目录存在
if [ ! -d "$WEB_ROOT" ]; then
    echo -e "${RED}警告: 目录 $WEB_ROOT 不存在，正在尝试创建...${PLAIN}"
    mkdir -p "$WEB_ROOT"
fi

# 生成随机文件名建议
RAND_NAME="sub_$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)"
read -p "请输入订阅文件名 (默认随机: $RAND_NAME): " input_filename
if [ -z "$input_filename" ]; then
    FINAL_FILENAME="$RAND_NAME"
else
    FINAL_FILENAME="$input_filename"
fi

FULL_SUB_PATH="$WEB_ROOT/$FINAL_FILENAME"

# 5. 生成核心处理脚本 (Updater)
echo -e "\n${YELLOW}[步骤 4/5] 生成自动处理脚本...${PLAIN}"

cat > "$UPDATER_SCRIPT" <<EOF
#!/bin/bash
# Auto Generated by Install Script

XUI_URL="$XUI_URL"
EXTERNAL_FILE="$EXTERNAL_NODES_FILE"
OUTPUT_FILE="$FULL_SUB_PATH"

# 1. Fetch Local X-UI Sub
LOCAL_BASE64=\$(curl -s -L "\$XUI_URL")

# 2. Decode (Try to handle different base64 behaviors)
LOCAL_NODES=\$(echo "\$LOCAL_BASE64" | tr -d '\n' | base64 -d 2>/dev/null)
if [ -z "\$LOCAL_NODES" ]; then
    # Fallback for systems strictly requiring correct padding or options
    LOCAL_NODES=\$(echo "\$LOCAL_BASE64" | tr -d '\n' | base64 -di 2>/dev/null)
fi

# 3. Read External Nodes
EXT_NODES=""
if [ -f "\$EXTERNAL_FILE" ]; then
    EXT_NODES=\$(cat "\$EXTERNAL_FILE")
fi

# 4. Merge and Encode
# Ensure newlines between merges
MERGED_CONTENT=\$(echo -e "\${LOCAL_NODES}\n\${EXT_NODES}")

# Remove empty lines and encode back to base64
FINAL_BASE64=\$(echo "\$MERGED_CONTENT" | grep "vless://" | base64 | tr -d '\n')

# 5. Write to Web Dir
echo "\$FINAL_BASE64" > "\$OUTPUT_FILE"

echo "订阅已更新: \$OUTPUT_FILE \$(date)"
EOF

chmod +x "$UPDATER_SCRIPT"
echo -e "${GREEN}处理脚本已生成: $UPDATER_SCRIPT${PLAIN}"

# 运行一次测试
echo -e "正在执行初次合并..."
bash "$UPDATER_SCRIPT"

# 6. 设置定时任务
echo -e "\n${YELLOW}[步骤 5/5] 自动化设置${PLAIN}"
read -p "是否添加 Crontab 定时任务，每10分钟自动更新一次? [y/n] " want_cron

if [[ "$want_cron" == "y" || "$want_cron" == "Y" ]]; then
    # 移除旧的任务（如果存在）防止重复
    crontab -l | grep -v "$UPDATER_SCRIPT" | crontab -
    # 添加新任务
    (crontab -l; echo "*/10 * * * * /bin/bash $UPDATER_SCRIPT >/dev/null 2>&1") | crontab -
    echo -e "${GREEN}定时任务已添加!${PLAIN}"
else
    echo -e "已跳过定时任务设置。"
fi

# 结束
# 获取本机 IP 用于展示
IPV4=$(curl -s4m8 ip.sb)
echo -e "\n${SKYBLUE}#############################################################${PLAIN}"
echo -e "${GREEN}部署完成！${PLAIN}"
echo -e "外部节点文件: ${YELLOW}$EXTERNAL_NODES_FILE${PLAIN} (如需增删节点，请编辑此文件)"
echo -e "核心处理脚本: ${YELLOW}$UPDATER_SCRIPT${PLAIN} (可手动运行测试)"
echo -e "-------------------------------------------------------------"
echo -e "你的聚合订阅地址为:"
echo -e "${SKYBLUE}http://${IPV4}/${FINAL_FILENAME}${PLAIN}"
echo -e "-------------------------------------------------------------"
echo -e "请在客户端添加此链接进行测试。"
